CREATE DATABASE IMDB
USE IMDB

CREATE TABLE Movies(
Id int PRIMARY KEY IDENTITY,
[Name] nvarchar(100) NOT NULL,
Duration INT ,
Point DECIMAL(1,1)
)


CREATE TABLE Genres(
	Id INT PRIMARY KEY IDENTITY,
	Name NVARCHAR(100)
)

CREATE TABLE MovieGenres(
	Id INT PRIMARY KEY IDENTITY,
	MovieId INT CONSTRAINT FK_MovieId FOREIGN KEY REFERENCES Movies(Id),
	GenreId INT CONSTRAINT FK_GenreId FOREIGN KEY REFERENCES Genres(Id)
)

CREATE TABLE Actors(
	Id INT PRIMARY KEY IDENTITY,
	Name NVARCHAR(100),
	Surname NVARCHAR(120)
)

CREATE TABLE MovieActers(
	Id INT PRIMARY KEY IDENTITY,
	MovieId INT CONSTRAINT FK_MovieActersId FOREIGN KEY REFERENCES Movies(Id),
	ActorId INT CONSTRAINT FK_AcrtorId FOREIGN KEY REFERENCES Actors(Id)
)

CREATE TABLE Directors(
	Id INT PRIMARY KEY IDENTITY,
	Fullname NVARCHAR(100),
	MovieId INT CONSTRAINT FK_MoviesId FOREIGN KEY REFERENCES Movies(Id)
)


SELECT Movies.Id,Movies.Name,Movies.Point,Genres.Name FROM Movies   
JOIN MovieGenres
ON 